spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: userdb
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    schemas: userdb
    table: history_table

secret-value: secretValue
jwt-token-expiration: 20