spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: userdb
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    schemas: userdb
    table: history_table

secret-value: secretValue
jwt:
  expiration:
    access-token: 60
    refresh-token: 480